<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="nHapi" Version="2.5.0.6" />
    <PackageReference Include="ObjectListView.Official" Version="2.9.1" />
  </ItemGroup>
</Project>